baseURL = 'https://example.org/'
languageCode = 'pt-br'
title = 'LK'

[menus]

  [[menus.main]]
    name = 'Expertise'
    pageRef = '/expertise'
    weight = 1

  [[menus.main]]
    name = 'Experiência'
    pageRef = '/experiencias'
    weight = 2

  [[menus.main]]
    name = 'Portifolio'
    pageRef = '/portifolio'
    weight = 3

  [[menus.main]]
    name = 'Contato'
    pageRef = '/contato'
    weight = 5

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
