baseURL = 'https://example.org/'
languageCode = 'pt-br'
title = 'LK'

[menus]
  [[menus.main]]
    name = 'Experiência'
    pageRef = '/experiencias'
    weight = 20

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
